using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class ClickHandler : MonoBehaviour
{
    public PlanetPlacement clickMovement; // Referencia al script ClickMovement adjunto al objeto que se mover치
    public Vector3 targetPosition; // La posici칩n a la que se mover치 el objeto al hacer clic en este GameObject
    public Vector3 targetScale; // La escala que se aplicar치 al objeto al hacer clic en este GameObject

    void OnMouseDown()
    {
        if (clickMovement != null)
        {
            clickMovement.MoveToPosition(targetPosition, targetScale);
        }
    }
}